package com.example.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.dto.Record;
import com.example.dto.RecordExample;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int countByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int deleteByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    List<Record> selectByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    Record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hours_record
     *
     * @mbggenerated Tue Feb 28 14:40:52 CST 2017
     */
    int updateByPrimaryKey(Record record);
}